microsoft/sample-app-aoai-chatGPT

.devcontainer/devcontainer.json
README.md
README_azd.md
azure.yaml
scripts/auth_init.ps1
scripts/auth_init.py
scripts/auth_init.sh
scripts/auth_update.ps1
scripts/auth_update.sh
scripts/loadenv.ps1
scripts/loadenv.sh
scripts/prepdocs.ps1
scripts/prepdocs.sh
start.sh

Previously, my README included instructions for users to set up a virtual environment or use a dev container. However, it's easy to miss that instruction, and then the scripts unexpectedly install packages into the main Python requirement.
This PR changes the scripts to create a venv in the root and use that venv's Python for all the commands. This is similar to what's done in https://github.com/pamelafox/azure-search-openai-demo/ except that repo creates multiple venvs, one for backend and one for scripts. Given the overlap between them, I think it's more straightforward to create

Use venv for scripts

---

scripts/loadenv.ps1
scripts/loadenv.sh

Fixes #59 
This PR adds conditionals to loadenv.sh and loadenv.ps1 to check that the azd command exists and that there's a current azd env. I tested by loading in a dev container with/without azd, and by deleting the .azure folder to simulate no environment.

Put checks in loadenv in case azd isnt around

---

README_azd.md
infra/main.bicep

Two small tweaks to azd experience:
* Add location recommendation to README (based on https://github.com/Azure-Samples/azure-search-openai-demo/ )
* Give the docprep module its own name. Otherwise you can get name collisions if you run this with multiple azd resource groups.

Add location to README, make module name unique

---

app.py

- adds support for vector search when using Azure OpenAI on your data
- adds support for document level access control when using Azure OpenAI on your data via AAD Auth and the MS Graph API
- resolves endpoint/domain name issues

Add support for vector search and document level access control

---

scripts/data_utils.py

- separate out tables (along with the last heading, the last line before the table, the first line after the table for context)
- chunk tables into mini tables (with retaining context and headers for each mini table)
- chunk non-table portions as usual (but separately from tables)
- merging non-table and table portions not handled yet

Improve chunking for tables in PDFs

---

app.py

This PR adds an `apim-request-id` key:value to the `stream_with_data` function making it available in the `result` object.

Feat: Add apim-request-id to stream_with_data response

---

app.py

This PR addresses a bug discovered [here](https://github.com/microsoft/sample-app-aoai-chatGPT/issues/366) due a nonexistent tool message when running the chat app without data. 
This bug was introduced because of a workflow issue with VScode that is now addressed.

[bug] Running chat without data fails on second message due to nonexistent tool message

---

app.py

This PR addresses the empty tool message in the history/update route. The frontend is currently sending an empty object for the tool message. A more robust solution addressing the frontend to come later.

Fix: Check for empty tool message in history/update

---

README.md

Add instructions for additional app settings for multi-worker and multi-thread processing.

Add scalability instructions to readme

---

scripts/data_utils.py

In this PR I'm adding support for docx and pptx so that if the user provides form recognizer resources, the script can ingest word and powetr point files through form recognizer.

- supporting docx and pptx in offline ingestion script via form recognizer

---

scripts/cosmos_mongo_vcore_data_preparation.py

if we don't set this environment variable, we can't get embedding vector by `get_embedding()` func at `data_utils.py`, and we face the `No chunks found. Please check the data path and chunk size.` error. so, we need to set `EMBEDDING_MODEL_KEY` at `cosmos_mongo_vcore_data_preparation.py`.
//repro step
1. cd scripts
2. python ./cosmos_mongo_vcore_data_preparation.py --cosmos-config ./cosmos_config.json --njobs=4 --embedding-model-endpoint https://<your-aoai-resource>.openai.azure.com/openai/deployments/<your-embedding-deploymentId>/embeddings?api-version=2023-03-15-preview --embedding-model-key "your-api-key"
3. we face the `No chunks found. Please check the data path and chunk size.` error

Set `EMBEDDING_MODEL_KEY` at cosmos_mongo_vcore_data_preparation.py

---

app.py
backend/utils.py

This solves two issues 1: Previously to achieve adding the feedback feature a `global message_id` was used this worked but a global variable wasn't desirable. 2: When the async work was merged in the use of the global variable made the feedback feature unusable at times. 
This reactor removes the use of the global variable and utilizes the correct assistant message id.
- Built and tested locally and in a deployed app
- backend only
- This is for all users
- No breaking changes

[Refactor] Remove global message_id from feedback implementation

---

app.py

`app.py` was not reloading static files after frontend changes causing an error.
`app.config["TEMPLATES_AUTO_RELOAD"] = True` adding this line fixed the issue
Built and ran locally
No frontend changes
This is for all users
No breaking changes

[fix] Auto reload templates

---

scripts/data_utils.py

1. Why is this change required?
Our chunking logic does not respect URL boundaries, so technically it is possible for the code to break a URL into two during chunking. One of our major customers YW recently encountered this (although for them, the main reason was Form Recognizer not correctly recognizing URLs that span across lines).
2. What problem does it solve?
Irrespective of Form Recognizer, we can make sure our chunking step does not break URLs. This PR ensures this for PDF documents that use Form Recognizer.
3. What scenario does it contribute to?
Same as 1 and 2
4. If it fixes an open issue, please link to the issue here.
The issue is being tracked outside of this repository.
5. Does this solve an issue or add a feature that *all* users of this sample app can benefit from? 
It …

protect urls during chunking

---

app.py

There was a bug that when the assistant couldn't respond with a relevant message (i.e. prompting hello over and over again) the assistant message would not be in the response exposing the tools message.
This PR remove the tool message from the request resulting in appropriate responses from the assistant.

[fix] Remove tool dictionary from messages list in the aoai request

---

app.py

Fix issue with keyerror in list comprehension

---

app.py
backend/auth/auth_utils.py
backend/security/ms_defender_utils.py

1. Simplify MS Defender integration
2. Enable MS Defender integration by default, if customer enabled Defender for AI plan, then customer will have rich security alerts in XDR (it is not possible to add API check if defender plan is enabled because for ARM control plane call, we need to know the subscription and resource group of the AOAI resource, and we do not always have that)
3. Remove port from source IP
4. Remove tenantid code, it is not working in API webapp

Simplify MS Defender integration & enable by default

---

.github/workflows/node.js.yml
frontend/package.json

The recent introduction of the plotly package has caused some issues with heap size during the build.
Adding a line to the package.json to fix this.

Add -max_old_space_size option to build section of package.json

---

frontend/src/pages/chat/Chat.tsx
static/index.html

Previously the "Stop Generating" button would show when there wasn't a message being generated. This was cause by the logic check if cosmodb was loading.
To address this we check if cosmodb `isLoading` and if there are messages in the messages array.

Hide Stop Generating button when no messages

---

.github/workflows/docker-image-build.yml
.github/workflows/docker-image-publish.yml

Docker login won't pull secrets from PRs created from forks, which is causing failure during the PR gate for testing that the docker image builds successfully.
We don't push anything in this workflow, so we should be able to remove the login step from it without causing issues to fix this.

Remove docker login step from the build workflow

---

README.md
app.py
backend/settings.py

Currently access to Azure OpenAI requires a key to be used. I wanted to enable entra ID based authentication. There is an issue for this: #190 
- make the setting of AZURE_OPENAI_KEY optional
- add description to README on how to configure RBAC

Eable entra ID authentication

---

.github/workflows/check-static-files.yml

A few checks on static files may be helpful for avoiding potential bugs, and for ensuring that PR contributors are aware of certain unsupported changes to the codebase.

Create a workflow for checks on static files

---

README.md
app.py

2 things:
- the documentation did not properly describe the variable DATASOURCE_TYPE
- prompt flow currently does not work, if AZURE_OPENAI_STREAM is set to true (probably the reason of #934, since AZURE_OPENAI_STREAM defaults to true)

describe DATASOURCE_TYPE & enable prompt flow even when AZURE_OPENAI_STREAM=true

---

README.md
app.py
backend/settings.py
frontend/src/api/models.ts
frontend/src/pages/layout/Layout.tsx
static/index.html

Many of the UI element are customizable now so I have added Show Chat History to that list.

[feature] Add env var to show/hide Chat History Button

---

frontend/src/pages/chat/Chat.tsx
frontend/src/pages/layout/Layout.tsx
frontend/src/state/AppProvider.tsx
frontend/src/state/AppReducer.tsx
static/index.html

I noticed when using a custom logo, there was a flash of the Contoso logo before the custom logo was available.
I have a set an isLoading bool so that we can know whether or not the ui settings are set particularly the logo. While is loading is true no logo is shown. When isLoading is false, we check for ui.logo and if true then show that one otherwise show the Contoso logo. 
https://github.com/microsoft/sample-app-aoai-chatGPT/assets/994856/b4abfbf0-804d-4c43-836f-b266c43ce900

[fix] Flashing Contoso logo when custom logo is present

---

backend/utils.py

*history_metadata* was inside *choices* object when formatting non streaming response from Prompt Flow endpoint

Fix error in first question when using PF

---

scripts/data_utils.py

This address the bug mentioned in #1034 where the data preparation script fails when the table is empty.
All this PR does is add a check to make sure there is a "span" of the text that each table corresponds to. If there is no such span, then it skips the table since that means it's just an empty table with no information.

Prevent ingestion failure on empty tables

---

scripts/data_utils.py

While running some tests with large documents, I modified the script for some quality-of-life improvements.
- More descriptive comments
- Now the image only scales up by 200% if either dimension is smaller than 3 inches
- Prevent a bug where the image didn't correspond to any text, so it would just insert the image in between every character
- Limit the number of replacements to 1, so it takes less time

Image ingestion QoL improvements

---

backend/utils.py

Modify the format for citations field in the promptflow response post processing stage, so that citation shows up in UI.Fixing issue reported: https://portal.microsofticm.com/imp/v5/incidents/details/540126530/summary
1. Why is this change required? 
Currently, when users point webapp to a promptflow endpoint instead of OYD, they are unable to see citations in the frontend and interact with them.
2. What problem does it solve?
Now citations show up and user can click and interact with them in Web App UI
3. What scenario does it contribute to?
Prompt flow endpoint integration
4. If it fixes an open issue, please link to the issue here.
Issue: https://portal.microsofticm.com/imp/v5/incidents/details/540126530/summary
5. Does this solve an issue or add a feature that *all* users of this …

Fix Citation Format for Prompt Flow Endpoint Responses

---

infra/main.bicep

The deployment location was hard coded to `eastus`.
This change changes this to use the value of `resourceGroup.location` instead.

Fixes deployment location of cosmosdb

---

backend/settings.py

The default value for auth_enabled should be true.

Set auth_emabled to true by default

---

requirements.txt

This commit fixes an issue highlighed in #1173. 
It occurs when you run a deployment from Azure AI Studio and choose the Web App, which links to this repo. The issue occurs when you try to run the app but it encounters an error and says "KeyError: 'PROVIDE_AUTOMATIC_OPTIONS'".

This fixes #1173

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.tsx

Default CDN being loaded by the initializeIcons method was decommissioned on January 15, 2025. See https://github.com/microsoft/fluentui/issues/33612
Fixes #1249 - Empty Icons
Updates call to initializeIcons() in index.tsx to reference a specific CDN location.

Update initializeIcons function call to load from new CDN location (Fixes #1249)

---

README.md
README_azd.md
app.py
backend/security/ms_defender_utils.py

user security context is component introduced in ms defender for cloud here https://learn.microsoft.com/en-us/azure/defender-for-cloud/gain-end-user-context-ai
this PR is for adding this object to the model args

User security context to model args instead of user json
