scripts/data_preparation.py
scripts/data_utils.py
scripts/readme.md

- Read model is faster and cheaper
- Layout model helps when table information is important to maintain and display

[Data prep] Make form recognizer Layout model optional, default to Read

---

scripts/readme.md

Add a line in the data preparation readme to remind user that there should not be duplicated pages in their data, because that could negatively impact AIQ.

add disclaimer to de-dup before data ingestion

---

scripts/data_utils.py

Add `chunk_id` to the index build. Fix `HTMLParser`'s title parsing logic.

add chunk_id and parsing title validation

---

scripts/data_utils.py

Preserve tags in HTML format while parsing HTML documents. Since Markdown processing also uses html for parsing, we will also preserve formatting for Markdown documents.
This would help citations to be well formatted and also improve quality of responses.

Preserve formatting for HTML and Markdown documents

---

infra/core/host/appservice.bicep

Since this is a user facing app, allowedApplications should be an empty list.
More details:
https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad?tabs=workforce-tenant#use-a-built-in-authorization-policy

Add allowed apps

---

WebApp.Dockerfile
app.py
requirements-dev.txt

- bump python version in Dockerfile
- resolve potential relative path traversal issue in Flask backend
- bump langchain version

Address vulnerabilities

---

README.md
app.py

Update README with clearer instructions. Remove old headers from the API call.

Update readme, remove deprecated headers from API call

---

scripts/data_preparation.py
scripts/data_utils.py

- use SDK for embeddings 
- small bug fixes for handling vector indexes
- update with encoding detection to address non-utf-8 encodings

Fixes for vector ingestion, file encoding

---

infra/db.bicep

Update the partition key for cosmosdb deployed with azd to the correct key.

Fix cosmosdb partition key for azd

---

scripts/data_utils.py

Remove adding any context from after the table as this can confuse the model to produce wrong results. (based on customer feedback)

remove adding context after the table

---

requirements-dev.txt

added chardet dependency

---

scripts/cosmos_config.json
scripts/cosmos_mongo_vcore_data_preparation.py
scripts/readme.md

- Adding Cosmos data preparation script
Outstanding work: will add a separate readme for cosmos mongo vcore cases

Adding Cosmos data preparation

---

README.md
app.py

- Adds new setting "DEBUG" which if set to "true" will enable logging level DEBUG in Python backend.
- Adds additional debug logs
- Fix issue with document-level access control where filter string is not passed when user is not a member of any groups or there's an error fetching user groups.

Add debug logging and fix DLAC

---

TEST_CASE_FLOWS.md

This PR adds a markdown file to document the test flows for testing the Sample app.

[FEATURE] Add markdown file to document test case flows

---

infrastructure/deployment.json

fix elasticsearch settings in deployment template

---

scripts/data_utils.py

Add telemetry header to track usage of form recognizer service.

[FormRecognizer] Add telemetry header to track usage

---

README.md
WebApp.Dockerfile
infrastructure/deployment.json

- add the scalability for the docker image
- add the documentation
- add the default settings on the app service for the one click azure depyloment.

add the scalability for the docker image

---

.github/workflows/docker-image.yml

Dockerfile has a bug - remove the workflow trigger for now.

Don't automatically update docker for now

---

scripts/data_utils.py

**1. Why is this change required?**
The version of the Python OpenAI library was increased to 1.x in this project. The current use of the implementation of the Python OpenAI API is no longer supported by the new version.
Specifically, it is no longer possible to call the API using `openai` from `import openai` directly.
The new API version requires the creation of a `client` object, using the `AzureOpenAI` class.
**2. What problem does it solve?**
The creation of embeddings using e.g., `prepdocs.py` failed due to this incompatibility. 
**3. What scenario does it contribute to?**
The creation of embeddings using `prepdocs.sh` as part of the deployment to Azure using `azd up` or by a manual call will work again.  
**4. Does this solve an issue or add a feature that *all* users of this …

Migrate embedding creation to new Python OpenAI library version 1.x

---

start.cmd

Add port and reload flag to start.cmd

---

app.py

UI won't be update by .env file while local hosting
.env file should be loaded before applying UI content

[fix] load .env before apply UI

---

tools/data_collection.py

Script for collecting data from endpoint against test set.
Given a test set, use the web app functionality to collect responses from the endpoint.

data collection tool

---

app.py
backend/auth/auth_utils.py

Defender for AI is part of Defender for Cloud and to provide advanced threat protection to customers we need gen-ai apps to be instrumented as this PR suggests
This PR is part1 - Add functionality and make it opt-in to start tests and do some demos.
I plan to add a check whether Defender for AI is enabled in another PR

support passing user-info to AOAI for Defender for cloud

---

scripts/data_utils.py

remove duplicates..

---

backend/settings.py

Some of the common search settings are not used in the ARM deployment template used by the Azure OpenAI Studio as originally thought.  Moving those settings to each search settings class for now until the template can be updated.
Also fixed an issue with the filter parameter for Azure Search.

Fix for common settings and filter parameter

---

backend/history/cosmosdbservice.py
backend/settings.py

Chat history not working due to account key not being optional.
Allow optional account key when setting up cosmosdb.

No task db error on deployed apps

---

.github/workflows/docker-image-build.yml
.github/workflows/docker-image-publish.yml

The docker login in the CI pipelines is broken.  Attempting to fix it.

Fix docker login issue in CI pipeline

---

.github/workflows/stale-issues.yml

We have a lot of issues accruing, many of which are old and probably not actionable at this time.  The workflow checked in in this PR should mark issues as stale and then close them after a certain period of time.

Create workflow for closing stale issues

---

.github/workflows/python-app.yml
requirements-dev.txt

We have a need for increased test coverage.  For now, I'm adding changes to measure the coverage only, but will create a second PR in the future to create a status check which will fail at a TBD threshold.

Enable code coverage measurement for tests
